### ISSUE TITLE
Publish correct build to NPM

### ISSUE THREAD

**Issue by konrad-garus** [jetbridge/axios-jwt#1]
npmjs.com shows version 1.0.4 of this plugin: https://www.npmjs.com/package/axios-jwt

It seems to be quite different from master in this repo. In that version, `TokenRefreshRequest` returns `Promise<string>` and does not seem to ever update the refresh token.

Looking at [master](https://github.com/jetbridge/axios-jwt/blob/master/src/index.ts#L94) here, the refresh function returns `Promise<IAuthTokens>`. Interestingly enough, package.json declares this to be version 1.0.1.

**Comment by revmischa** [comment]
Okay I just pushed my changes and released 1.0.5

**Comment by konrad-garus** [comment]
Wow, thanks for fast reply!

The versions do match now, but it might be a step backwards. How can I refresh the refresh token now?

Actually, in my case I don't even have a separate refresh token. There is just one token, and it should be used to obtain a new one before it expires (perhaps with `setTimeout`?). Does this scenario sound like something you would like to support here?

**Comment by revmischa** [comment]
do you want refreshToken exported? 
feel free to send a PR with what you want. a preemptive refresh would be a nice feature for others to have too.

**Comment by revmischa** [comment]
If you have any ideas please feel free to open a PR. It would be very nice to do a preemptory refresh in order to not block later requests. Good idea
