### ISSUE TITLE
Request without the interceptor

### ISSUE THREAD

**Issue by gpessa** [jetbridge/axios-jwt#2]
I would like to know if there is a way to not use the interceptor in some calls, sometimes I have call which do not require the tokens.

**Comment by revmischa** [comment]
I normally just use axios directly for such calls instead of using my configured AxiosInstance
What interface did you have in mind?

**Comment by ziplokk1** [comment]
@gpessa just use the global axios instance. or create an axios instance that isn't configured with the interceptor.
