### ISSUE TITLE
Can not refresh token

### ISSUE THREAD

**Issue by motionrus** [jetbridge/axios-jwt#4]
When i try refresh token, i get infinity loop with Promise

**Comment by revmischa** [comment]
Can you post the code?
Is it possible the access token you get back is expired already? Does it have an expiration?

**Comment by motionrus** [comment]
no problem: 
```const requestRefresh: TokenRefreshRequest = async (
  refreshToken: string
): Promise<string> => {
  // perform refresh
  return (await axios.post(refreshEndpoint, { token: refreshToken })).data
    .access_token;
};
```
This code i found in **README.md**, in my curious when i used fetch, my cycle stopped. I Think that, axios inside trying call refreshToken when trying call axios when trying call refreshToken. I will try use fetch and i think it will solve my infinity loop problem

**Comment by motionrus** [comment]
i tried use fetch and this solved my problem
```javascript
const requestRefresh: TokenRefreshRequest = async (
  refreshToken: string
): Promise<string> => {
  return await fetch(`${TOKEN}refresh/`, {
    method: "POST",
    mode: "cors",
    cache: "no-cache",
    credentials: "same-origin",
    headers: {
      "Content-Type": "application/json",
    },
    redirect: "follow",
    referrer: "no-referrer",
    body: JSON.stringify({refresh: refreshToken}),
  })
    .then(response => response.json())
    .then(response => response.access)
}
```

**Comment by revmischa** [comment]
If you have an idea of what's wrong, feel free to send along a patch! :)

**Comment by revmischa** [comment]
In the source:
```
    // do refresh with default axios client (we don't want our interceptor applied for refresh)
    const res = await requestRefresh(refreshToken)
```
Maybe this should be clearer? Or we can set some global variable while performing refresh to disable checking to see if we need a refresh while the refresh is happening?

**Comment by motionrus** [comment]
Maybe it's my mistake, because i don't use instance axios. I use global axios.
```javascript
import axios from "axios"
useAuthTokenInterceptor(axios, {requestRefresh})
```

**Comment by revmischa** [comment]
Ah then yeah you have one global axios that has the interceptor applied. This wouldn't work for the reason you discovered above. What can be done to help make this simpler for users?

**Comment by ziplokk1** [comment]
I had the same problem. See my comment in #5 . Just make sure that you're using the *global* axios in the refresh request, and an axios instance in any api calls.

**Comment by mvanroon** [comment]
@revmischa I've clarified this even more in the updated installation instructions in https://github.com/jetbridge/axios-jwt/pull/17. I think this issue can be closed.
