### ISSUE TITLE
Allow a different storage.

### ISSUE THREAD

**Issue by Rawnly** [jetbridge/axios-jwt#40]
Hello, I would like to store my credentials inside a cookie. I need them available for SSR reasons. Having the ability to specify a custom `storage` would be nice. 

It could be done extending the existing [`Storage` interface][mdn-storage] and adding it to the config object.

[mdn-storage]: https://developer.mozilla.org/en-US/docs/Web/API/Storage

**Comment by revmischa** [comment]
I agree that cookie support is needed. It's generally considered best practice because of HttpOnly and friends. Which I didn't know when I wrote this module.

**Comment by Rawnly** [comment]
I took a look at the code (which I contributed in the past) and I think that for such a  radical change it ha s to ne rethinked from ground… if u’re interested I can try something in the weekend.

**Comment by revmischa** [comment]
Sure maybe a 2.0 version would make sense

**Comment by prince272** [comment]
Inspired by @jetbridge, I created an http-client.js that stores, clears, transmits and automatically refresh JWT authentication tokens. Supports both localstorage and cookie storage. [Check it out here](https://gist.github.com/prince272/385ccd1068bdcd9d5129c760043e5308)

**Comment by mvanroon** [comment]
You should consider opening up a pull request :-)

**Comment by prince272** [comment]
Okay sure.

**Comment by Rawnly** [comment]
What about a general `Storage` interface so the user can configure it as preferred from the `interceptor`? (Like the refresh function)

**Comment by greenyas** [comment]
Made a PR that would allow usage of cookies as well: https://github.com/jetbridge/axios-jwt/pull/48

**Comment by Rawnly** [comment]
this one and #45 can be closed once #48 is released :)
