### ISSUE TITLE
localstorage is not defined

### ISSUE THREAD

**Issue by moshfrid** [jetbridge/axios-jwt#45]
It seem that the storage abstraction, specifically exporting localstorage in the storage.ts file, is breaking server-side code.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/20837433/200320478-82fe5a42-aad0-41bf-ad70-faad2867f809.png">

**Comment by revmischa** [comment]
Probably it should be getStorage()?

**Comment by Rawnly** [comment]
> Probably it should be getStorage()?

Yes it should, but maybe refactoring the whole lib using a class and passing storage as dependency would be even better. In that way the user can specify any storage and use it even on server-side (and it closes #40)
