### ISSUE TITLE
undefined window and Synchronous isLoggedIn

### ISSUE THREAD

**Issue by moshfrid** [jetbridge/axios-jwt#55]
For some reason, the new swappable storage interface has caused isLoggedIn to not excecute properly on initial page load. For example, in my app im using it to set the ui state for logged in vs not logged in users and now it returns false on page load (onmount useeffect) and true only later, rendering the wrong ui state.

Furthermore, when trying to build the app, getBrowserLocalStorage is causing a ReferenceError: window is not defined t be thrown

**Comment by moshfrid** [comment]
@revmischa any chance you can make a release?

**Comment by revmischa** [comment]
ok

**Comment by CaioAugustoo** [comment]
just faced this problem rn lol thank u

**Comment by moshfrid** [comment]
thanks!
