### ISSUE TITLE
No dist/ folder from clean install

### ISSUE THREAD

**Issue by daxaxelrod** [jetbridge/axios-jwt#72]
Hi Again! Fresh install of 4.0.1 throws an error because package.json says to look in /dist/index but its not there

**Comment by revmischa** [comment]
That's odd, seems like it's in the package:
https://www.npmjs.com/package/axios-jwt/v/4.0.1?activeTab=code

![Screenshot 2024-02-07 at 8 47 28 PM](https://github.com/jetbridge/axios-jwt/assets/245131/d9644e3d-26ae-4253-bffa-083f1a35e3cf)

Any idea what could be wrong?

**Comment by daxaxelrod** [comment]
Yes you are totally right! Must've been some local caching issue. Thanks!
