### ISSUE TITLE
getAccessToken() returns undefined

### ISSUE THREAD

**Issue by aurarius1** [jetbridge/axios-jwt#76]
Hi, 
the getAccessToken (or isLoggedIn) returns undefined if the authTokenInterceptor has not been applied yet. This is of course because of the missing applyStorage call, but the library doesn't export this at root level (import {applyStorage} from 'axios-jwt' doesn't work). Rather one has to import from the dist folder directly. 

Should I create a pull request that just adds the export in the index.ts file? 

Kind regards 
Lukas

**Comment by revmischa** [comment]
Sure feel free!

**Comment by aurarius1** [comment]
Perfect, I'll create one on the weekend, it's a little easier in terms of time then.
